parameters:
  seed: 114
  loss_weights:
    huber: 1.0
    w_mass_mmd0: 0.0
    w_mass_mmd1: 0.0
    w0_mass_mae: 0.0
    w1_mass_mae: 0.0
    dinu_pt: 0.01
    higgs_mass: 1.0
    angular_loss_mmd: 100.0
    nu_mass: 0.0

  batch_size: 256
  epochs: 1024
  learning_rate: 1.0e-4
  gradient_clip_val: 0.0
  d_model: 128
  n_heads: 16
  # dataloader settings (set num_workers > 0 only if stable)
  num_workers: 10
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 8

data:
  categories: null
  val_frac: 0.05
  test_frac: 0.01

paths:
  saved_path: "/root/work/ww-pcres/hww_pcres_regressor_nofold_no_w_mmd"
  data_path: "/root/data/danning_h5/ypeng/mc20_qe_v4_recotruth_merged.h5"
